name: Deploy to ECR Public

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build, tag, and push image to Amazon ECR Public
        run: |
          docker build -t manu-ecr .

          # Log in to Amazon ECR Public (no need for AWS access keys)
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r6d4t7o4

          # Tag the image
          docker tag manu-ecr:latest public.ecr.aws/r6d4t7o4/manu-ecr:latest

          # Push the image to Amazon ECR Public
          docker push public.ecr.aws/r6d4t7o4/manu-ecr:latest
