name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Build Docker image
        run: |
          docker build -t my-docker-image:latest .
        working-directory: ./

      - name: Tag Docker image
        run: |
          docker tag my-docker-image:latest ${{ steps.login-ecr.outputs.server_url }}/manu-ecr:latest
        working-directory: ./

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.server_url }}/manu-ecr:latest
        working-directory: ./

      - name: Complete
        run: echo "Docker image built and pushed to ECR repository 'manu-ecr' successfully."
